<?php declare(strict_types = 1);

use OriNette\Auth\Tracy\AuthPanel;

/** @var AuthPanel $panel */

?>
<div class='tracy-inner'>
	<div class='tracy-inner-container'>
		<table>
			<tr>
				<td>Firewall</td>
				<td>Logged in</td>
			</tr>
			<?php foreach ($panel->getFirewalls() as $firewall): ?>
				<tr>
					<td><?= $firewall->getNamespace() ?></td>
					<td><?= $firewall->isLoggedIn() ? 'yes' : 'no' ?></td>
				</tr>
			<?php endforeach; ?>
		</table>
	</div>
</div>
